### ISSUE TITLE
env doesn't work with ;

### ISSUE THREAD

**Issue by plicease** [plicease/Clustericious-Admin#2]
with config:

```
---
env:
  FOO: whatever
clusters:
  cluster1:
    - host1
    - host2
```

this works:
```
% clad cluster1 'printenv FOO'
```

but this doesn't:
```
% clad cluster1 'cd /tmp; printenv FOO'
```
